# Generated by Django 3.1 on 2020-11-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawn',
            name='xpos',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pawn',
            name='ypos',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
